package com.work;

import java.io.*;
import java.util.*;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

import com.Instructors.Instructor;
import com.Instructors.Instructors;

public class FlatMap {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		
		 List<List<Integer> > number = new ArrayList<>();
	       
	        // adding the elements to number arraylist
	        number.add(Arrays.asList(1, 2));
	        number.add(Arrays.asList(3, 4));
	        number.add(Arrays.asList(5, 6));
	        number.add(Arrays.asList(7, 8));
	       
	        System.out.println("List of list-" + number);
	        
	        
	        List<Integer> flatList= number.stream().flatMap(list -> list.stream()).collect(Collectors.toList());
       
        // printing the list
        System.out.println("List generate by flatMap-"
                           + flatList);
        
        
        // lets use map() to convert list of fruit
        List list = number.stream()
                        .map(s -> s.size())
                        .collect(Collectors.toList());
        System.out.println("List generated by map-" + list);
        
        
        
        //Get a list of all the courses which instructors offers
        Set<String> instructorsCourses = Instructors.getAll().stream()
                                        .map(Instructor::getCourses)
                                        .flatMap(List::stream)
                                        .collect(Collectors.toSet());
        System.out.println(instructorsCourses);
	       

	}

}
